import { createContext, useContext, useState } from 'react'

const translations = {
  az: {
    // Navbar
    'nav.menu': 'Menyu',
    'nav.gallery': 'Atmosfer',
    'nav.reservation': 'Rezervasiya',
    'nav.team': 'Kollektivimiz',
    'nav.contact': 'Əlaqə',
    'nav.careers': 'Vakansiya',
    'nav.search.placeholder': 'Məhsul axtar... (məs: latte, limonad)',
    'nav.search.close': 'Bağla',
    'nav.search.found': 'nəticə tapıldı · Menyuya keçmək üçün seç',
    'nav.search.notfound': 'üçün nəticə tapılmadı',

    // Hero
    'hero.label': 'Coffee House · Sumqayıt',
    'hero.subtitle': 'Hər Gün Yeni Bir Dadla Başla',
    'hero.cta.menu': 'Menyu',
    'hero.cta.delivery': 'Çatdırılma',
    'hero.cta.reviews': 'Rəylər',
    'hero.scroll': 'scroll',

    // InfoStrip
    'info.wifi': 'Wi-Fi',
    'info.address': 'Ünvan',
    'info.hours': 'İş saatları',
    'info.hours.value': 'Hər gün: 08:00 – 01:00',
    'info.pet': 'Pet-Friendly',
    'info.pet.value': 'Kiçik dostunu gətir!',

    // Menu
    'menu.title': 'Menyu',
    'menu.subtitle': 'İçkilərdən yeməklərə hər şey burada olsun',
    'menu.cat.all': 'Hamısı',
    'menu.cat.breakfast': 'Səhər Yeməyi',
    'menu.cat.rolls': 'Rollar',
    'menu.cat.salads': 'Salatlar',
    'menu.cat.sandwich': 'Sendviç',
    'menu.cat.bowls': 'Kəsalar',
    'menu.cat.desserts': 'Desertlər',
    'menu.cat.coffee-hot': 'İsti Qəhvə',
    'menu.cat.coffee-cold': 'Soyuq Qəhvə',
    'menu.cat.drinks': 'İçkilər',
    'menu.group.foods': 'Yeməklər',
    'menu.group.specials': 'Xüsusi Təkliflər',
    'menu.specials.banner': 'Kampaniya saat 16:00-a qədər keçərlidir',
    'menu.items': 'məhsul',
    'menu.empty': 'Bu bölmədə məhsul yoxdur.',
    'menu.sub.breakfast': 'Günə dadlı başlanğıc',
    'menu.sub.rolls': 'Dadla dolu rulonlar',
    'menu.sub.salads': 'Təzə və təravətli',
    'menu.sub.sandwich': 'Doyumlu ləzzətlər',
    'menu.sub.bowls': 'Bol dad, böyük porsiya',
    'menu.sub.desserts': 'Şirin sonluq',
    'menu.sub.coffee-hot': 'Klassik və alternativ dadlar',
    'menu.sub.coffee-cold': 'Soyuq qəhvə ləzzətləri',
    'menu.sub.drinks': 'Geniş içki menyusu',
    'menu.sec.classic': 'Classic Hot Coffees',
    'menu.sec.alt': 'Alternative Coffee',
    'menu.sec.smoothies': 'Smoothies',
    'menu.sec.lemonade': 'Classic Lemonade',
    'menu.sec.icetea': 'Iced Tea',
    'menu.sec.cocktails': 'Non-Alcoholic Cocktails',
    'menu.sec.mocktails': 'Mocktails',
    'menu.sec.signature': 'Siqnature İçkilər',
    'menu.sec.milkshakes': 'Milkshakes',
    'menu.sec.extrabar': 'Extra Bar',
    'menu.sec.tea': 'Tea',
    'menu.sec.bubbletea': 'Bubble Tea',
    'menu.sec.fresh': 'Fresh Juices',
    'menu.sec.coffeebeans': 'Coffee Beans',
    'menu.heading.coldcoffee': 'Cold Coffee',
    'menu.heading.rolls': 'Rolls',
    'menu.heading.salads': 'Salads',
    'menu.heading.sandwich': 'Sandwich',
    'menu.heading.bagettes': 'Bagetlər',
    'menu.heading.bowls': 'Bowls',
    'menu.heading.desserts': 'Desserts',
    'menu.heading.specials': 'Special Offers',
    'menu.order.title': 'Sifariş Forması',
    'menu.order.name': 'Ad',
    'menu.order.phone': 'Telefon',
    'menu.order.table': 'Masa nömrəsi',
    'menu.order.payment': 'Ödəniş yalnız kartla həyata keçirilir',
    'menu.order.label': 'Sifariş:',
    'menu.order.total': 'Cəmi',
    'menu.order.confirm': 'Sifarişi Təsdiqlə',
    'menu.whatsapp.header': '🛒 Yeni Sifariş - Kaffa Cup',
    'menu.whatsapp.payment': '💳 Ödəniş: Kartla',

    // Gallery
    'gallery.title': 'Atmosfer',
    'gallery.subtitle': 'Sumqayıtın ən isti məkanı',
    'gallery.card1.label': 'İçəri Görüntü',
    'gallery.card1.sub': 'Neon işarə, isti atmosfer',
    'gallery.card2.label': 'Açıq Teras – Gündüz',
    'gallery.card2.sub': 'Günəşli teras, yaşıl kollar',
    'gallery.card3.label': 'Gecə Terası',
    'gallery.card3.sub': 'İşıqlı dam, gecə atmosferi',

    // Team
    'team.title': 'Kollektivimiz',
    'team.subtitle': 'Kaffa Cup ailəsi',

    // Reviews
    'reviews.title': 'Müştəri Rəyləri',
    'reviews.cta': 'Bütün Rəylərə Bax',

    // Contact / Map
    'contact.title': 'Bizi Tapın',
    'contact.address': 'Ünvan',
    'contact.phone': 'Telefon',
    'contact.hours': 'İş Saatları',
    'contact.hours.value': 'Hər gün 08:00 – 01:00',
    'contact.wolt': 'Wolt-da sifariş et',
    'contact.maps': 'Google Maps-də aç',

    // Footer
    'footer.desc': 'Sumqayıtın ən sevimli qəhvə məkanı. Keyfiyyətli qəhvə, dadlı yeməklər və rahat atmosfer.',
    'footer.hours.label': 'Hər gün:',
    'footer.hours.value': '08:00 – 01:00',
    'footer.links': 'Keçidlər',
    'footer.contact': 'Əlaqə',
    'footer.nav.menu': 'Menyu',
    'footer.nav.gallery': 'Atmosfer',
    'footer.nav.reservation': 'Rezervasiya',
    'footer.nav.team': 'Komanda',
    'footer.nav.contact': 'Əlaqə',
    'footer.nav.careers': 'Komandamıza Qoşul',
    'footer.nav.privacy': 'Məxfilik Siyasəti',
    'footer.maps': 'Google Maps-də aç',
    'footer.wolt': 'Wolt-da sifariş et',
    'footer.copyright': '© 2026 Kaffa Cup. Bütün hüquqlar qorunur.',

    // Careers
    'careers.label': 'Kaffa Cup · Komanda',
    'careers.title': 'Komandamıza Qoşul',
    'careers.desc': 'Kaffa Cup ailəsinə qoşul — Sumqayıtın ən sevimli qəhvə məkanında enerjik bir komandanın hissəsi ol.',
    'careers.perk1.title': 'Komanda ruhu',
    'careers.perk1.desc': 'Mehriban, energetik bir komanda ilə çiyin-çiyinə işləyərsən',
    'careers.perk2.title': 'Rahat iş saatları',
    'careers.perk2.desc': 'Tam yaxud part-time seçimi — sənə uyğun smen qrafiki, çevik planlaşdırma imkanı',
    'careers.perk3.title': 'İnkişaf',
    'careers.perk3.desc': 'Barista sertifikatları, qəhvə kursları və karyera yüksəlişi',
    'careers.open': 'Açıq Vəzifələr',
    'careers.open.note': 'Uyğun vəzifə görmürsənsə, narahat olma — müraciət formasında "Digər" seç və özün haqqında yaz.',
    'careers.pos.barista': 'Barista',
    'careers.pos.cashier': 'Kassir',
    'careers.pos.waiter': 'Ofisiant',
    'careers.pos.kitchen': 'Mətbəx işçisi',
    'careers.pos.courier': 'Çatdırılma kuryer',
    'careers.pos.other': 'Digər',
    'careers.form.title': 'Sorğu yolla',
    'careers.form.desc': 'Formu doldurun, WhatsApp vasitəsilə bizimlə əlaqə saxlayın',
    'careers.form.name': 'Ad Soyad *',
    'careers.form.name.ph': 'Məsələn: Aytən Hüseynova',
    'careers.form.phone': 'Telefon *',
    'careers.form.phone.ph': '+994 50 000 00 00',
    'careers.form.pos': 'Hansı vəzifə üçün? *',
    'careers.form.pos.ph': 'Vəzifə seçin...',
    'careers.form.msg': 'Özün haqqında qısaca (istəyə görə)',
    'careers.form.msg.ph': 'Niyə Kaffa Cup-da işləmək istəyirsən? Əvvəlki təcrübən var mı?',
    'careers.form.submit': 'WhatsApp ilə Müraciət Et',
    'careers.form.hint': 'Müraciətin WhatsApp-da açılacaq. Göndər düyməsini basaraq bizimlə əlaqə saxla.',
    'careers.form.success': 'WhatsApp açıldı! Mesajını göndər, tezliklə əlaqə saxlayacağıq.',
    'careers.err.name': 'Ad soyad tələb olunur',
    'careers.err.phone': 'Telefon tələb olunur',
    'careers.err.pos': 'Vəzifə seçin',
    'careers.wa.title': 'Salam! Kaffa Cup-da işləmək istəyirəm. 🍵',

    // Privacy
    'privacy.label': 'Kaffa Cup · Hüquqi Sənəd',
    'privacy.title': 'Məxfilik Siyasəti',
    'privacy.updated': 'Son yenilənmə: 2026',
    'privacy.intro': 'Biz, Kaffa Cup komandası olaraq, sizin məxfilik hüquqlarınıza hörmət göstərir və şəxsi məlumatlarınızın təhlinə, istifadəsinə və paylaşılmasına son dərəcə ehtiramla yanaşırıq.',
    'privacy.closing': 'Kaffa Cup kimi, sizin məxfilik hüquqlarınızı qorumağa və şəxsi məlumatlarınızı etik və ciddi şəkildə işləməyə öz hörmətimizi bildirir və sizə dərin təşəkkürümüzü bildiririk.',
    'privacy.board': 'Kaffa Cup İdarə Heyəti',
    'privacy.back': 'Əsas səhifəyə qayıt',
    'privacy.s1.title': 'Məxfilik Siyasətinin Məqsədi',
    'privacy.s1.text': 'Kaffa Cup, müvafiq qanun və tənzimləyici normativ sənədlərə uyğun şəkildə, fəaliyyətinin məqsədi üçün lazım olan şəxsi məlumatları toplamaq və istifadə etmək üçün məxfilik siyasəti tətbiq edir. Məqsədimiz, sizinlə əlaqələrimizi daha yaxşı tənzimləmək, təklif etdiyimiz xidmətləri təkmilləşdirmək və münasibətlərimizi daha səmərəli və maraqlı etməkdir.',
    'privacy.s2.title': 'Toplanan Məlumatlar',
    'privacy.s2.text': 'Kaffa Cup veb saytına daxil olduğunuzda, sizdən adınız, elektron poçt ünvanınız, telefon nömrəniz (sifariş və rezervasiya zamanı) və digər şəxsi məlumatlarınız tələb oluna bilər. Bu məlumatlar, sizə daha yaxın və münasibətli xidmətlər təqdim etmək, sifarişlərinizi düzgün idarə etmək və ümumi veb sayt təcrübənizi yaxşılaşdırmaq üçün istifadə edilir.',
    'privacy.s3.title': 'Şəxsi Məlumatların İstifadəsi',
    'privacy.s3.text': 'Topladığımız şəxsi məlumatları, yalnız sizin razılığınızla və sizin məxfilik haqqınıza hörmətlə istifadə edirik. Bu məlumatları sizə təqdim edilən xidmətlərlə bağlı əlaqə saxlamaq, sifarişləriniz haqqında bildirişlər göndərmək, rəylərinizi qiymətləndirmək və xidmətlərimizi təkmilləşdirmək üçün istifadə edə bilərik.',
    'privacy.s4.title': 'Məlumatların Paylaşılması',
    'privacy.s4.text': 'Kaffa Cup, üçüncü tərəf tərəfindən sizin şəxsi məlumatlarınızın əldə edilməsi üçün sizin razılığınız olmadan şəxsi məlumatlarınızı satmır, kirayəyə verməz və ya bəyan etməz. Bu məlumatları yalnız sizin xidmətlərimizə göstərən tərəfdaşlarımızla (məsələn, çatdırılma xidməti) əlaqədar qanunvericilik tələblərinə riayət edərək paylaşırıq.',
    'privacy.s5.title': 'Şəxsi Məlumatların Qorunması',
    'privacy.s5.text': 'Kaffa Cup, sizin şəxsi məlumatlarınızı qorumağa və təhlil etməyə yönəlik tədbirlər göstərir. Sizdən topladığımız şəxsi məlumatları təhlil etmək və saxlamaq üçün müstəqil tədbirlər tətbiq edirik.',
    'privacy.s6.title': 'İstifadəçi Hüquqları',
    'privacy.s6.text': 'Sizin şəxsi məlumatlarınıza dair qaydalar və tənzimləmələr çərçivəsində sizin müstəqil hüquqlarınıza hörmət edirik. Siz, şəxsi məlumatlarınızı dəyişdirmək, məxfilik siyasətimizdə dəyişiklik etmək və ya şəxsi məlumatlarınızın təhlilini istəmək kimi hüquqlara sahibsiniz.',

    // Terms
    'terms.label': 'Kaffa Cup · Hüquqi Sənəd',
    'terms.title': 'İstifadə Şərtləri',
    'terms.updated': 'Son yenilənmə: 2026',
    'terms.intro': 'Kaffa Cup-un veb saytından və xidmətlərindən istifadə etməklə, aşağıda göstərilən istifadə şərtlərini qəbul etmiş sayılırsınız. Zəhmət olmasa bu şərtləri diqqətlə oxuyun.',
    'terms.s1.title': 'Şərtlərin Qəbulu',
    'terms.s1.text': 'Bu sayta daxil olaraq və ya xidmətlərimizdən istifadə edərək siz bu istifadə şərtlərini tam qəbul etmiş hesab olunursunuz. Əgər bu şərtlərlə razı deyilsinizsə, saytımızdan istifadəni dayandırmanızı xahiş edirik.',
    'terms.s2.title': 'Xidmətlər',
    'terms.s2.text': 'Kaffa Cup, Sumqayıt şəhərində fəaliyyət göstərən qəhvə evi olaraq onlayn menyu, masa rezervasiyası, çatdırılma (Wolt vasitəsilə) və cashback loyallıq proqramı kimi xidmətlər təqdim edir. Xidmətlər əvvəlcədən xəbərdarlıq edilmədən dəyişdirilə bilər.',
    'terms.s3.title': 'İstifadəçi Öhdəlikləri',
    'terms.s3.text': 'Saytımızdan istifadə edərək siz: doğru məlumat təqdim etməyə, xidmətləri qeyri-qanuni məqsədlər üçün istifadə etməməyə, digər istifadəçilərin hüquqlarına hörmət etməyə və tətbiq olunan bütün qanunlara riayət etməyə razılıq verirsiniz.',
    'terms.s4.title': 'Ödəniş Şərtləri',
    'terms.s4.text': 'Kaffa Cup-da bütün ödənişlər Azərbaycan Manatı (₼) ilə həyata keçirilir. Sifarişin ləğvi zamanı ödənişin qaytarılması məsələsi hər hal üzrə ayrıca nəzərdən keçirilir. Çatdırılma sifarişlərindəki ödəniş şərtləri Wolt platformasının qaydalarına tabedir.',
    'terms.s5.title': 'Cashback Proqramı',
    'terms.s5.text': 'Kaffa Cup cashback proqramı çərçivəsində hər alışdan 5% geri qaytarılır. Cashback yalnız şəxsi promo kodu ilə kassada təsdiqlənən alışlara şamil edilir. Kaffa Cup cashback proqramının şərtlərini öncədən xəbərdarlıq etmədən dəyişdirmək hüququnu özündə saxlayır.',
    'terms.s6.title': 'Məsuliyyətin Məhdudlaşdırılması',
    'terms.s6.text': 'Kaffa Cup, saytın işinin fasilələri, texniki xətalar və ya üçüncü tərəf xidmətlərindən (Wolt çatdırılma və s.) yaranan problemlər üçün məsuliyyət daşımır. Bütün mübahisəli məsələlər Azərbaycan Respublikasının qüvvədə olan qanunvericiliyinə uyğun həll edilir.',
    'terms.closing': 'Bu şərtlərlə bağlı hər hansı sualınız olarsa, bizimlə əlaqə saxlayın. Kaffa Cup komandası sizə kömək etməkdən məmnuniyyət duyur.',
    'terms.board': 'Kaffa Cup İdarə Heyəti',
    'terms.back': 'Əsas səhifəyə qayıt',
    'terms.nav.privacy': 'Məxfilik Siyasəti',
    'terms.nav.terms': 'İstifadə Şərtləri',

    'menu.popular': 'Ən çox sifariş edilən',
    'menu.add': '+ Əlavə Et',
    'menu.price': 'Qiymət',
    'menu.addcart': 'Səbətə Əlavə Et',
  },

  ru: {
    'nav.menu': 'Меню',
    'nav.gallery': 'Атмосфера',
    'nav.reservation': 'Резервация',
    'nav.team': 'Команда',
    'nav.contact': 'Контакт',
    'nav.careers': 'Вакансии',
    'nav.search.placeholder': 'Поиск товаров... (напр: латте, круассан)',
    'nav.search.close': 'Закрыть',
    'nav.search.found': 'результатов найдено · Нажмите для перехода в меню',
    'nav.search.notfound': 'ничего не найдено по запросу',

    'hero.label': 'Кофейня · Сумгайыт',
    'hero.subtitle': 'Начни каждый день с нового вкуса',
    'hero.cta.menu': 'Меню',
    'hero.cta.delivery': 'Доставка',
    'hero.cta.reviews': 'Отзывы',
    'hero.scroll': 'scroll',

    'info.wifi': 'Wi-Fi',
    'info.address': 'Адрес',
    'info.hours': 'Часы работы',
    'info.hours.value': 'Каждый день: 08:00 – 01:00',
    'info.pet': 'Pet-Friendly',
    'info.pet.value': 'Приводи питомца!',

    'menu.title': 'Меню',
    'menu.subtitle': 'Всё здесь — от напитков до блюд',
    'menu.cat.all': 'Все',
    'menu.cat.breakfast': 'Завтрак',
    'menu.cat.rolls': 'Роллы',
    'menu.cat.salads': 'Салаты',
    'menu.cat.sandwich': 'Сэндвич',
    'menu.cat.bowls': 'Боулы',
    'menu.cat.desserts': 'Десерты',
    'menu.cat.coffee-hot': 'Горячий кофе',
    'menu.cat.coffee-cold': 'Холодный кофе',
    'menu.cat.drinks': 'Напитки',
    'menu.group.foods': 'Еда',
    'menu.group.specials': 'Специальные предложения',
    'menu.specials.banner': 'Акция действует до 16:00',
    'menu.items': 'позиций',
    'menu.empty': 'В этом разделе пока нет продуктов.',
    'menu.sub.breakfast': 'Вкусное начало дня',
    'menu.sub.rolls': 'Роллы, полные вкуса',
    'menu.sub.salads': 'Свежо и аппетитно',
    'menu.sub.sandwich': 'Сытные вкусности',
    'menu.sub.bowls': 'Много вкуса, большая порция',
    'menu.sub.desserts': 'Сладкое завершение',
    'menu.sub.coffee-hot': 'Классические и альтернативные вкусы',
    'menu.sub.coffee-cold': 'Холодные кофейные наслаждения',
    'menu.sub.drinks': 'Широкое меню напитков',
    'menu.sec.classic': 'Классический горячий кофе',
    'menu.sec.alt': 'Альтернативный кофе',
    'menu.sec.smoothies': 'Смузи',
    'menu.sec.lemonade': 'Лимонад Классик',
    'menu.sec.icetea': 'Холодный чай',
    'menu.sec.cocktails': 'Безалкогольные коктейли',
    'menu.sec.mocktails': 'Мокtейли',
    'menu.sec.signature': 'Сигнатурные напитки',
    'menu.sec.milkshakes': 'Молочные коктейли',
    'menu.sec.extrabar': 'Extra Bar',
    'menu.sec.tea': 'Чай',
    'menu.sec.bubbletea': 'Бабл Ти',
    'menu.sec.fresh': 'Свежевыжатые Соки',
    'menu.sec.coffeebeans': 'Кофе в Зёрнах',
    'menu.heading.coldcoffee': 'Холодный кофе',
    'menu.heading.rolls': 'Роллы',
    'menu.heading.salads': 'Салаты',
    'menu.heading.sandwich': 'Сэндвич',
    'menu.heading.bagettes': 'Багеты',
    'menu.heading.bowls': 'Боулы',
    'menu.heading.desserts': 'Десерты',
    'menu.heading.specials': 'Специальные предложения',
    'menu.order.title': 'Форма заказа',
    'menu.order.name': 'Имя',
    'menu.order.phone': 'Телефон',
    'menu.order.table': 'Номер стола',
    'menu.order.payment': 'Оплата производится только картой',
    'menu.order.label': 'Заказ:',
    'menu.order.total': 'Итого',
    'menu.order.confirm': 'Подтвердить заказ',
    'menu.whatsapp.header': '🛒 Новый заказ - Kaffa Cup',
    'menu.whatsapp.payment': '💳 Оплата: Картой',

    'gallery.title': 'Атмосфера',
    'gallery.subtitle': 'Самое уютное место Сумгайыта',
    'gallery.card1.label': 'Интерьер',
    'gallery.card1.sub': 'Неоновая вывеска, тёплая атмосфера',
    'gallery.card2.label': 'Открытая Терраса – Днём',
    'gallery.card2.sub': 'Солнечная терраса, зелёные кусты',
    'gallery.card3.label': 'Ночная Терраса',
    'gallery.card3.sub': 'Освещённая крыша, ночная атмосфера',

    'team.title': 'Наша команда',
    'team.subtitle': 'Семья Kaffa Cup',

    'reviews.title': 'Отзывы клиентов',
    'reviews.cta': 'Смотреть все отзывы',

    'contact.title': 'Найдите нас',
    'contact.address': 'Адрес',
    'contact.phone': 'Телефон',
    'contact.hours': 'Часы работы',
    'contact.hours.value': 'Каждый день 08:00 – 01:00',
    'contact.wolt': 'Заказать на Wolt',
    'contact.maps': 'Открыть в Google Maps',

    'footer.desc': 'Самое любимое кофе-место Сумгайыта. Качественный кофе, вкусная еда и уютная атмосфера.',
    'footer.hours.label': 'Каждый день:',
    'footer.hours.value': '08:00 – 01:00',
    'footer.links': 'Ссылки',
    'footer.contact': 'Контакты',
    'footer.nav.menu': 'Меню',
    'footer.nav.gallery': 'Атмосфера',
    'footer.nav.reservation': 'Резервация',
    'footer.nav.team': 'Команда',
    'footer.nav.contact': 'Контакт',
    'footer.nav.careers': 'Работай с нами',
    'footer.nav.privacy': 'Политика конфиденциальности',
    'footer.maps': 'Открыть в Google Maps',
    'footer.wolt': 'Заказать на Wolt',
    'footer.copyright': '© 2026 Kaffa Cup. Все права защищены.',

    'careers.label': 'Kaffa Cup · Команда',
    'careers.title': 'Работай с нами',
    'careers.desc': 'Присоединяйся к семье Kaffa Cup — стань частью энергичной команды в самом любимом кофе-месте Сумгайыта.',
    'careers.perk1.title': 'Командный дух',
    'careers.perk1.desc': 'Работай плечом к плечу с дружной, энергичной командой',
    'careers.perk2.title': 'Гибкий график',
    'careers.perk2.desc': 'Полная или частичная занятость — удобный сменный график, гибкое планирование',
    'careers.perk3.title': 'Развитие',
    'careers.perk3.desc': 'Сертификаты бариста, кофейные курсы и карьерный рост',
    'careers.open': 'Открытые вакансии',
    'careers.open.note': 'Не нашёл подходящую вакансию? Выбери «Другое» и расскажи о себе.',
    'careers.pos.barista': 'Бариста',
    'careers.pos.cashier': 'Кассир',
    'careers.pos.waiter': 'Официант',
    'careers.pos.kitchen': 'Работник кухни',
    'careers.pos.courier': 'Курьер доставки',
    'careers.pos.other': 'Другое',
    'careers.form.title': 'Подать заявку',
    'careers.form.desc': 'Заполните форму и свяжитесь с нами через WhatsApp',
    'careers.form.name': 'Имя Фамилия *',
    'careers.form.name.ph': 'Например: Иван Иванов',
    'careers.form.phone': 'Телефон *',
    'careers.form.phone.ph': '+994 50 000 00 00',
    'careers.form.pos': 'На какую должность? *',
    'careers.form.pos.ph': 'Выберите должность...',
    'careers.form.msg': 'Расскажи о себе (по желанию)',
    'careers.form.msg.ph': 'Почему хочешь работать в Kaffa Cup? Есть ли опыт?',
    'careers.form.submit': 'Отправить заявку через WhatsApp',
    'careers.form.hint': 'Заявка откроется в WhatsApp. Нажми «Отправить» для связи с нами.',
    'careers.form.success': 'WhatsApp открыт! Отправь сообщение — мы свяжемся с тобой.',
    'careers.err.name': 'Имя обязательно',
    'careers.err.phone': 'Телефон обязателен',
    'careers.err.pos': 'Выберите должность',
    'careers.wa.title': 'Здравствуйте! Хочу работать в Kaffa Cup. 🍵',

    'privacy.label': 'Kaffa Cup · Юридический документ',
    'privacy.title': 'Политика конфиденциальности',
    'privacy.updated': 'Последнее обновление: 2026',
    'privacy.intro': 'Мы, команда Kaffa Cup, уважаем ваши права на конфиденциальность и относимся к обработке, использованию и передаче ваших персональных данных с максимальным уважением.',
    'privacy.closing': 'Kaffa Cup выражает своё уважение к вашим правам на конфиденциальность и обязуется обрабатывать ваши персональные данные этично и ответственно.',
    'privacy.board': 'Совет директоров Kaffa Cup',
    'privacy.back': 'Вернуться на главную',
    'privacy.s1.title': 'Цель политики конфиденциальности',
    'privacy.s1.text': 'Kaffa Cup применяет политику конфиденциальности для сбора и использования персональных данных, необходимых для осуществления своей деятельности, в соответствии с действующим законодательством. Наша цель — улучшить взаимодействие с вами, совершенствовать услуги и делать наши отношения более эффективными.',
    'privacy.s2.title': 'Собираемые данные',
    'privacy.s2.text': 'При посещении сайта Kaffa Cup от вас могут быть запрошены имя, адрес электронной почты, номер телефона (при заказе и резервировании) и другие персональные данные. Эти данные используются для предоставления персонализированных услуг, управления заказами и улучшения вашего опыта на сайте.',
    'privacy.s3.title': 'Использование персональных данных',
    'privacy.s3.text': 'Мы используем собранные персональные данные только с вашего согласия и с уважением к вашему праву на конфиденциальность. Данные могут использоваться для связи по вопросам услуг, отправки уведомлений о заказах, оценки отзывов и совершенствования наших услуг.',
    'privacy.s4.title': 'Передача данных третьим лицам',
    'privacy.s4.text': 'Kaffa Cup не продаёт, не передаёт в аренду и не раскрывает ваши персональные данные третьим лицам без вашего согласия. Данные передаются только партнёрам, оказывающим услуги (например, службе доставки), в срочных случаях и в соответствии с требованиями законодательства.',
    'privacy.s5.title': 'Защита персональных данных',
    'privacy.s5.text': 'Kaffa Cup принимает меры по защите и обработке ваших персональных данных. Мы применяем независимые меры для анализа и хранения собранных от вас данных.',
    'privacy.s6.title': 'Права пользователей',
    'privacy.s6.text': 'Мы уважаем ваши независимые права в рамках правил и норм, касающихся ваших персональных данных. Вы вправе изменять свои данные, вносить изменения в нашу политику конфиденциальности или запрашивать анализ своих персональных данных.',

    'terms.label': 'Kaffa Cup · Юридический документ',
    'terms.title': 'Условия использования',
    'terms.updated': 'Последнее обновление: 2026',
    'terms.intro': 'Используя веб-сайт и услуги Kaffa Cup, вы считаетесь принявшим условия использования, указанные ниже. Пожалуйста, внимательно прочитайте эти условия.',
    'terms.s1.title': 'Принятие условий',
    'terms.s1.text': 'Заходя на этот сайт или используя наши услуги, вы считаетесь полностью принявшим эти условия использования. Если вы не согласны с этими условиями, просим вас прекратить использование сайта.',
    'terms.s2.title': 'Услуги',
    'terms.s2.text': 'Kaffa Cup, кофейня в городе Сумгаит, предоставляет услуги онлайн-меню, бронирования столов, доставки (через Wolt) и программы лояльности с кэшбэком. Услуги могут быть изменены без предварительного уведомления.',
    'terms.s3.title': 'Обязательства пользователя',
    'terms.s3.text': 'Используя наш сайт, вы соглашаетесь предоставлять достоверную информацию, не использовать услуги в незаконных целях, уважать права других пользователей и соблюдать все применимые законы.',
    'terms.s4.title': 'Условия оплаты',
    'terms.s4.text': 'Все платежи в Kaffa Cup осуществляются в азербайджанских манатах (₼). Вопрос о возврате платежа при отмене заказа рассматривается индивидуально. Условия оплаты доставки подчиняются правилам платформы Wolt.',
    'terms.s5.title': 'Программа кэшбэка',
    'terms.s5.text': 'В рамках программы кэшбэка Kaffa Cup с каждой покупки возвращается 5%. Кэшбэк начисляется только на покупки, подтверждённые на кассе с личным промокодом. Kaffa Cup оставляет за собой право изменять условия программы кэшбэка без предварительного уведомления.',
    'terms.s6.title': 'Ограничение ответственности',
    'terms.s6.text': 'Kaffa Cup не несёт ответственности за перебои в работе сайта, технические ошибки или проблемы, возникшие из-за сторонних сервисов (доставка Wolt и т.д.). Все спорные вопросы решаются в соответствии с действующим законодательством Азербайджанской Республики.',
    'terms.closing': 'Если у вас есть вопросы по этим условиям, свяжитесь с нами. Команда Kaffa Cup будет рада помочь вам.',
    'terms.board': 'Совет директоров Kaffa Cup',
    'terms.back': 'Вернуться на главную',
    'terms.nav.privacy': 'Политика конфиденциальности',
    'terms.nav.terms': 'Условия использования',

    'menu.popular': 'Самый популярный',
    'menu.add': '+ Добавить',
    'menu.price': 'Цена',
    'menu.addcart': 'Добавить в корзину',
  },

  en: {
    'nav.menu': 'Menu',
    'nav.gallery': 'Atmosphere',
    'nav.reservation': 'Reservation',
    'nav.team': 'Our Team',
    'nav.contact': 'Contact',
    'nav.careers': 'Careers',
    'nav.search.placeholder': 'Search products... (e.g. latte, lemonade)',
    'nav.search.close': 'Close',
    'nav.search.found': 'results found · Click to go to menu',
    'nav.search.notfound': 'no results found for',

    'hero.label': 'Coffee House · Sumgait',
    'hero.subtitle': 'Start Every Day with a New Taste',
    'hero.cta.menu': 'Menu',
    'hero.cta.delivery': 'Delivery',
    'hero.cta.reviews': 'Reviews',
    'hero.scroll': 'scroll',

    'info.wifi': 'Wi-Fi',
    'info.address': 'Address',
    'info.hours': 'Working Hours',
    'info.hours.value': 'Every day: 08:00 – 01:00',
    'info.pet': 'Pet-Friendly',
    'info.pet.value': 'Bring your little friend!',

    'menu.title': 'Menu',
    'menu.subtitle': 'Everything here, from drinks to dishes',
    'menu.cat.all': 'All',
    'menu.cat.breakfast': 'Breakfast',
    'menu.cat.rolls': 'Rolls',
    'menu.cat.salads': 'Salads',
    'menu.cat.sandwich': 'Sandwich',
    'menu.cat.bowls': 'Bowls',
    'menu.cat.desserts': 'Desserts',
    'menu.cat.coffee-hot': 'Hot Coffee',
    'menu.cat.coffee-cold': 'Cold Coffee',
    'menu.cat.drinks': 'Drinks',
    'menu.group.foods': 'Food',
    'menu.group.specials': 'Special Offers',
    'menu.specials.banner': 'Offer valid until 16:00',
    'menu.items': 'items',
    'menu.empty': 'There are no products in this section yet.',
    'menu.sub.breakfast': 'A delicious start to the day',
    'menu.sub.rolls': 'Rolls full of flavour',
    'menu.sub.salads': 'Fresh and refreshing',
    'menu.sub.sandwich': 'Hearty flavours',
    'menu.sub.bowls': 'Big taste, big portion',
    'menu.sub.desserts': 'Sweet endings',
    'menu.sub.coffee-hot': 'Classic and alternative tastes',
    'menu.sub.coffee-cold': 'Cold coffee delights',
    'menu.sub.drinks': 'Wide drink selection',
    'menu.sec.classic': 'Classic Hot Coffees',
    'menu.sec.alt': 'Alternative Coffee',
    'menu.sec.smoothies': 'Smoothies',
    'menu.sec.lemonade': 'Classic Lemonade',
    'menu.sec.icetea': 'Iced Tea',
    'menu.sec.cocktails': 'Non-Alcoholic Cocktails',
    'menu.sec.mocktails': 'Mocktails',
    'menu.sec.signature': 'Signature Drinks',
    'menu.sec.milkshakes': 'Milkshakes',
    'menu.sec.extrabar': 'Extra Bar',
    'menu.sec.tea': 'Tea',
    'menu.sec.bubbletea': 'Bubble Tea',
    'menu.sec.fresh': 'Fresh Juices',
    'menu.sec.coffeebeans': 'Coffee Beans',
    'menu.heading.coldcoffee': 'Cold Coffee',
    'menu.heading.rolls': 'Rolls',
    'menu.heading.salads': 'Salads',
    'menu.heading.sandwich': 'Sandwich',
    'menu.heading.bagettes': 'Baguettes',
    'menu.heading.bowls': 'Bowls',
    'menu.heading.desserts': 'Desserts',
    'menu.heading.specials': 'Special Offers',
    'menu.order.title': 'Order Form',
    'menu.order.name': 'Name',
    'menu.order.phone': 'Phone',
    'menu.order.table': 'Table Number',
    'menu.order.payment': 'Payment is by card only',
    'menu.order.label': 'Order:',
    'menu.order.total': 'Total',
    'menu.order.confirm': 'Confirm Order',
    'menu.whatsapp.header': '🛒 New Order - Kaffa Cup',
    'menu.whatsapp.payment': '💳 Payment: Card',

    'gallery.title': 'Atmosphere',
    'gallery.subtitle': 'The warmest place in Sumgait',
    'gallery.card1.label': 'Interior',
    'gallery.card1.sub': 'Neon sign, warm atmosphere',
    'gallery.card2.label': 'Open Terrace – Daytime',
    'gallery.card2.sub': 'Sunny terrace, green bushes',
    'gallery.card3.label': 'Night Terrace',
    'gallery.card3.sub': 'Lit rooftop, night atmosphere',

    'team.title': 'Our Team',
    'team.subtitle': 'Kaffa Cup family',

    'reviews.title': 'Customer Reviews',
    'reviews.cta': 'View All Reviews',

    'contact.title': 'Find Us',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.hours': 'Working Hours',
    'contact.hours.value': 'Every day 08:00 – 01:00',
    'contact.wolt': 'Order on Wolt',
    'contact.maps': 'Open in Google Maps',

    'footer.desc': "Sumgait's most beloved coffee spot. Quality coffee, delicious food and a cosy atmosphere.",
    'footer.hours.label': 'Every day:',
    'footer.hours.value': '08:00 – 01:00',
    'footer.links': 'Links',
    'footer.contact': 'Contact',
    'footer.nav.menu': 'Menu',
    'footer.nav.gallery': 'Atmosphere',
    'footer.nav.reservation': 'Reservation',
    'footer.nav.team': 'Team',
    'footer.nav.contact': 'Contact',
    'footer.nav.careers': 'Work With Us',
    'footer.nav.privacy': 'Privacy Policy',
    'footer.maps': 'Open in Google Maps',
    'footer.wolt': 'Order on Wolt',
    'footer.copyright': '© 2026 Kaffa Cup. All rights reserved.',

    'careers.label': 'Kaffa Cup · Team',
    'careers.title': 'Work With Us',
    'careers.desc': "Join the Kaffa Cup family — become part of an energetic team at Sumgait's most beloved coffee spot.",
    'careers.perk1.title': 'Team Spirit',
    'careers.perk1.desc': 'Work shoulder to shoulder with a friendly, energetic team',
    'careers.perk2.title': 'Flexible Hours',
    'careers.perk2.desc': 'Full or part-time — a schedule that works for you, flexible planning',
    'careers.perk3.title': 'Growth',
    'careers.perk3.desc': 'Barista certificates, coffee courses and career advancement',
    'careers.open': 'Open Positions',
    'careers.open.note': "Don't see your role? Choose \"Other\" and tell us about yourself.",
    'careers.pos.barista': 'Barista',
    'careers.pos.cashier': 'Cashier',
    'careers.pos.waiter': 'Waiter',
    'careers.pos.kitchen': 'Kitchen Staff',
    'careers.pos.courier': 'Delivery Courier',
    'careers.pos.other': 'Other',
    'careers.form.title': 'Apply Now',
    'careers.form.desc': 'Fill in the form and contact us via WhatsApp',
    'careers.form.name': 'Full Name *',
    'careers.form.name.ph': 'E.g. Jane Smith',
    'careers.form.phone': 'Phone *',
    'careers.form.phone.ph': '+994 50 000 00 00',
    'careers.form.pos': 'Which position? *',
    'careers.form.pos.ph': 'Select a position...',
    'careers.form.msg': 'Tell us about yourself (optional)',
    'careers.form.msg.ph': 'Why do you want to work at Kaffa Cup? Do you have experience?',
    'careers.form.submit': 'Apply via WhatsApp',
    'careers.form.hint': 'Your application will open in WhatsApp. Hit Send to reach us.',
    'careers.form.success': "WhatsApp opened! Send the message — we'll get back to you soon.",
    'careers.err.name': 'Full name is required',
    'careers.err.phone': 'Phone number is required',
    'careers.err.pos': 'Please select a position',
    'careers.wa.title': "Hello! I'd like to work at Kaffa Cup. 🍵",

    'privacy.label': 'Kaffa Cup · Legal Document',
    'privacy.title': 'Privacy Policy',
    'privacy.updated': 'Last updated: 2026',
    'privacy.intro': 'We, the Kaffa Cup team, respect your privacy rights and treat the processing, use and sharing of your personal data with the utmost care.',
    'privacy.closing': 'Kaffa Cup expresses its respect for your privacy rights and commits to processing your personal data ethically and responsibly.',
    'privacy.board': 'Kaffa Cup Board of Directors',
    'privacy.back': 'Back to Home',
    'privacy.s1.title': 'Purpose of Privacy Policy',
    'privacy.s1.text': 'Kaffa Cup applies a privacy policy to collect and use personal data necessary for its operations, in accordance with applicable laws and regulations. Our goal is to better manage our relationship with you, improve the services we offer and make our interactions more effective.',
    'privacy.s2.title': 'Data Collected',
    'privacy.s2.text': 'When you visit the Kaffa Cup website, you may be asked to provide your name, email address, phone number (for orders and reservations) and other personal data. This information is used to provide you with personalised services, manage your orders and improve your overall website experience.',
    'privacy.s3.title': 'Use of Personal Data',
    'privacy.s3.text': 'We use collected personal data only with your consent and with respect for your privacy rights. This data may be used to contact you about services, send notifications about your orders, evaluate feedback and improve our services.',
    'privacy.s4.title': 'Data Sharing',
    'privacy.s4.text': 'Kaffa Cup does not sell, rent or disclose your personal data to third parties without your consent. We share data only with partners providing services (e.g. delivery service) in urgent cases and in compliance with legal requirements.',
    'privacy.s5.title': 'Protection of Personal Data',
    'privacy.s5.text': 'Kaffa Cup takes measures to protect and process your personal data. We implement independent measures to analyse and store data collected from you.',
    'privacy.s6.title': 'User Rights',
    'privacy.s6.text': 'We respect your independent rights within the framework of rules and regulations concerning your personal data. You have the right to modify your data, request changes to our privacy policy, or request an analysis of your personal data.',

    'terms.label': 'Kaffa Cup · Legal Document',
    'terms.title': 'Terms of Use',
    'terms.updated': 'Last updated: 2026',
    'terms.intro': 'By using the Kaffa Cup website and services, you are deemed to have accepted the terms of use set out below. Please read these terms carefully.',
    'terms.s1.title': 'Acceptance of Terms',
    'terms.s1.text': 'By accessing this site or using our services, you are deemed to have fully accepted these terms of use. If you do not agree to these terms, please stop using our site.',
    'terms.s2.title': 'Services',
    'terms.s2.text': 'Kaffa Cup, a coffee house in Sumgait, provides services including online menu, table reservations, delivery (via Wolt) and a cashback loyalty programme. Services may be changed without prior notice.',
    'terms.s3.title': 'User Obligations',
    'terms.s3.text': 'By using our site, you agree to provide accurate information, not to use the services for illegal purposes, to respect the rights of other users and to comply with all applicable laws.',
    'terms.s4.title': 'Payment Terms',
    'terms.s4.text': 'All payments at Kaffa Cup are made in Azerbaijani Manat (₼). The question of refunding a payment upon order cancellation is considered on a case-by-case basis. Payment terms for delivery orders are subject to the Wolt platform rules.',
    'terms.s5.title': 'Cashback Programme',
    'terms.s5.text': 'Under the Kaffa Cup cashback programme, 5% is returned on every purchase. Cashback applies only to purchases confirmed at the till with a personal promo code. Kaffa Cup reserves the right to change the terms of the cashback programme without prior notice.',
    'terms.s6.title': 'Limitation of Liability',
    'terms.s6.text': 'Kaffa Cup is not responsible for interruptions in site operation, technical errors or problems arising from third-party services (Wolt delivery, etc.). All disputed matters are resolved in accordance with the current legislation of the Republic of Azerbaijan.',
    'terms.closing': 'If you have any questions about these terms, please contact us. The Kaffa Cup team will be happy to help you.',
    'terms.board': 'Kaffa Cup Board of Directors',
    'terms.back': 'Back to Home',
    'terms.nav.privacy': 'Privacy Policy',
    'terms.nav.terms': 'Terms of Use',

    'menu.popular': 'Best seller',
    'menu.add': '+ Add',
    'menu.price': 'Price',
    'menu.addcart': 'Add to Cart',
  },
}

const LangContext = createContext()

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('az')
  const t = (key) => translations[lang]?.[key] ?? translations['az']?.[key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
